### ISSUE TITLE
Timestamp should encode milliseconds, not seconds

### ISSUE THREAD

**Issue by larsyencken** [ararslan/ULID.jl#1]
According to https://github.com/alizain/ulid, the ULID timestamp portion represents the integer number of milliseconds since epoch.

This implementation encodes seconds instead, which makes its timestamps off by 1000 from other implementations.

It should be very easy to fix, I'll try to make a PR.

**Comment by ararslan** [comment]
Thanks for pointing that out. A PR would be great.
